title: HocoNomNom
description: A blog about eating out in Howard County, Maryland
url: https://hoconomnom.com
future: true
permalink: /:year/:month/:day/:title:output_ext
paginate: 15
paginate_path: "/page:num/"
excerpt_separator: <!--more-->
timezone: America/New_York
twitter:
  username: hoconomnom
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
