title: HocoNomNom
description: A blog about eating out in Howard County, Maryland
url: https://hoconomnom.com
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"