title: HocoNomNom
description: A blog about eating out in Howard County, Maryland
url: https://hoconomnom.com
future: false
paginate: 20
paginate_path: "/page:num/"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-seo-tag
  - jekyll-feed